FROM debian:stretch

RUN apt-get update && \
    apt-get install -y \
        default-libmysqlclient-dev \
        libsasl2-dev \
        libssl-dev \
        python-dev \
        python-pip && \
    pip install --no-cache-dir \
        tox==3.1.0 \
        mysqlclient==1.3.7

RUN mkdir /app
COPY . /app

RUN rm /app/superset_config.py